### ISSUE TITLE
ErrImagePull and Error ImagePullBackOff

### ISSUE THREAD

**Issue by opotmans** [3scale/zync#264]
Hello,

Today, when i start the openshift and the 3scale platform I received this message at the level of the different containers: Zync - porta - apicast - ...

Failed | Error: ErrImagePull
-- | --
Back-off pulling image "quay.io/3scale/porta@sha256:375da101e660055962bbf4ea8e42acac145bc224fc1ba01c3e1dd5aef02dbc4d"
Error: ImagePullBackOff 

If I made a test at the level of docker...
docker pull quay.io/3scale/porta
Using default tag: latest
Trying to pull repository quay.io/3scale/porta ... 
manifest for quay.io/3scale/porta:latest not found

After checking on quay.io, I observed that an update was made 17 hours ago. only the nightly is  present
![image](https://user-images.githubusercontent.com/23280026/67149859-cd0f2b00-f2b0-11e9-8216-cc0019784145.png)

Could you please update the registry to make the installation working again.

Thanks 

Olivier

**Comment by guicassolato** [comment]
Hello, @opotmans. Thanks for reporting this as it will allow us to explain a little bit about how 3scale upstream images work.

We don’t always tag `latest` as it can mean different things for each component of 3scale and neither this is required for deployments on Openshift. 3scale upstream operators/templates define Openshift ImageStreams from the `nightly` tag, which is based on `master` branch of each component and ephemeral – i.e. its SHA ref may change quite often.

In order to refresh the ImageStream SHA ref and fix your current deployment still based on upstream images, you must run `oc import-image amp-zync`, and analogously for each other image you mentioned – `amp-system` (porta), `amp-apicast`, perhaps also `amp-backend`, etc.

If you want to prevent that from happening again in the future, please use a stable version of 3scale operators/templates of any of our previous supported releases.

**Comment by opotmans** [comment]
Hello, @guicassolato. thanks for your input. Effectively, the imagestream approach is not common for me :-) thanks to take time to explain that. So, I executed the proposed command for amp-zync, amp-backend, amp-system and amp-apicast the image streams show the update. All containers works except the system-app and the system-sphinx which the same error (Image pull back-off) and in the logs failed to pull image quay.io/3scale/porta where the manifest is not found. Both containers are linked to the same image
I check that the command oc import-image amp-system. this command works (no error) but error is always there for the installation of the container
When I analyse the oc import-image amp-system result, I observed that two sha256 are present:
- one starting with 8B8c67...
- one starting with 375da
it seems that the first one is downloaded but not the second one and the error for the deployment of the container is linked to it.
Could you please help me ?

[result_amp_system.txt](https://github.com/3scale/zync/files/3760941/result_amp_system.txt)

For your information, for the installation, I used this command oc new-app \ --param WILDCARD_DOMAIN="$(minishift ip).nip.io" \ --param AMP_RELEASE=2.4.0 \ -f https://red.ht/2HdoRPB  proposed in the guideline of the web site : https://3scale.github.io/use

Do you have another approach to install the product ? You told me that we have an operator, is it the operator on the GitHub? I saw that it's alpha? 
Thanks for your help
Regards

Olivier

**Comment by guicassolato** [comment]
@opotmans, the 2 SHAs you see after `oc import-image` are the new one to be pulled (identified with a `*`) and the one to be replaced. `375da101` is not so old, only 5 days ago, so you should be fine jumping directly to ` 8b8c6775`. Only by refreshing the ImageStream, `system-app`, `system-sidekiq` and `system-sphinx` should redeploy automatically and the failing pods get terminated and replaced. If you are still getting some "Image pull back-off" failures after that, check the events of the deployment.

You can find more about deploying to Openshift at https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.6/html/installing_3scale/onpremises-installation.

As for the operator, yes, the upstream is on GH: https://github.com/3scale/3scale-operator. The repo also hosts latest version of the Openshift templates as alternative. I recommend you to go with the `-eval` options non-production deployments.

**Comment by opotmans** [comment]
Hello @guiuecassolato,
It's really strange because I updated the imagestream with the oc import-image and the system continues to pull the old image 

Here is the screenshot:
![image](https://user-images.githubusercontent.com/23280026/67391059-21125c00-f59e-11e9-951b-a2157b2a94df.png)

So it seems that he doesn't taking into account the new image even if the update was made

after checking the deployment of the amp system i observed that he takes the latest tag for system developer and system developer instead the 2.4
![image](https://user-images.githubusercontent.com/23280026/67391343-c2011700-f59e-11e9-9e1c-613b828c27b4.png)
I changed the deployment yaml for the pods in error and it works now and the integration with Istio works
I will check now the operator..

thanks for your input and your help
Olivier
