### ISSUE TITLE
Generate license.xml THREESCALE-170

### ISSUE THREAD

**Issue by hallelujah** [3scale/zync#43]
Part of https://issues.jboss.org/browse/THREESCALE-170
We need to generate a licenses.xml for packages installed.

Basically it should be a rake task that will use https://github.com/3scale/license_finder_xml_reporter

**Comment by mikz** [comment]
Reverted by https://github.com/3scale/zync/pull/45 due to unintended rubocop change.

**Comment by hallelujah** [comment]
Closed by #46
