### ISSUE TITLE
 Enable ppc64le arch on zync

### ISSUE THREAD

**Issue by Abhijit-Mane** [3scale/zync#450]
Hi,

Thanks for the well articulated documentation that helped me build zync from source and run the tests outlined successfully on
IBM Power architecture (in short, ppc64le).

What is IBM Power architecture?
It is a RISC architecture and is IBM's prodigy, IBM has recently made its ISA (Instruction Set Architecture) opensource and in doing
so, they have significantly contributed back to the opensource community at large. Many of the pioneers of banking and HPC
industries today run on ppc64le architecture.

As an ongoing effort to enable open-source projects where Power architecture can add value, we are trying to enable this
project. We have seen absolutely no deviation in build/test instructions. I plan to submit a PR to enable build/testing on ppc64le.

What would it take from us to enable ppc64le in the CI/CD pipeline?
I see CircleCI is being used for the CI pipeline of this project. As of now, this is not supported for native compilation on ppc64le.
However, currently, we are enabled/certified on Travis & Jenkins and lots of open source communities have successfully used these
as CI/CD for ppc64le.

**Comment by Abhijit-Mane** [comment]
Thanks @hallelujah.
Attached is a set of .travis.yml and supporting scripts. I tested these on https://travis-ci.com where I can link my fork of upstream
zync. I am able to successfully build zync for ppc64le and also run tests (bundle exec rails test).

Please let me know what you think and I can submit a PR for incorporating these.

[travis.zip](https://github.com/3scale/zync/files/6608132/travis.zip)

**Comment by Abhijit-Mane** [comment]
Hi @hallelujah,

Checking if you got a chance to check this.

Thanks.
Abhijit

**Comment by Abhijit-Mane** [comment]
Hi @hallelujah. Gentle reminder if you got a chance to check.

Regards,
Abhijit

**Comment by krishvoor** [comment]
Hey Hery 👋 ,
Can please review this PR - https://github.com/3scale/zync/pull/464
