### ISSUE TITLE
Using system-provider service only resolves to first tenant API

### ISSUE THREAD

**Issue by abarrak** [3scale/zync#470]
Hi,

I'm trying to communicate with one tenant API from APICast Pod in multi-tenant setup.

Instead of hitting external route for the API, and since I'm in same `oc namespace` with `system-app`, I want to call `curl http://system-provider:3000/admin/api` directly but it only resolves to the first or master tenant and gives `404 - Not found` as response.

I tried to set HOST header with route of tenant, but it didn't work and I receive `301 - Moved Permanently` (?)

**Comment by hallelujah** [comment]
Hi @abarrak 

You will need those headers:

- `Host: the-domain`
- `X-Forwarded-Proto: https`

Tell us if that works
/cc @3scale/system

**Comment by abarrak** [comment]
Works like a charm!
Many many thanks @hallelujah, I was missing the `X-Forwarded-Proto`.
