### ISSUE TITLE
Add instructions on how to contribute

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [3scale/zync#55]
Add instructions to prospective contributors how they can contribute to this project, probably by writing a CONTRIBUTING.md file in the root and linking to it from README.md

**Comment by mikz** [comment]
I wonder what should be in the doc. 

There are some generally accepted rules like green status on github (tests + lint).

This project has no special requirements for contributions. Guess we should just link to some general ones?

Just open a PR and make sure the required statuses are green.

**Comment by andrewdavidmackenzie** [comment]
Maybe do the same as apicast repo. mention in readme and have a more detailed description in a file.

https://github.com/3scale/apicast/blob/master/.github/CONTRIBUTING.md

**Comment by mikz** [comment]
But my point is that file is 99% the same for all open source repos that have no special workflow. Open a PR to master, make the required statuses green and thats it.

I think specialised contributing doc is needed when the repository has special rules.

**Comment by andrewdavidmackenzie** [comment]
Not a biggie, but in general I would assume little and little about potential contributors....make it easy for newbies to contribute, some simple directions - how to setup dev env, build, test and then make PRs... and maybe tag "simple" issues for newbies to work on.... etc...

**Comment by mikz** [comment]
Closed by #72
