### ISSUE TITLE
NoMethodError in notifications#update (undefined method `find_or_create_by!' for #<OpenStruct attribute_names=[]>)

### ISSUE THREAD

**Issue by mikz** [3scale/zync#90]
## Error in Zync

`**NoMethodError** in **notifications#update**
undefined method find_or_create_by!' for #<OpenStruct attribute_names=[]>`

[View on Bugsnag](https://app.bugsnag.com/3scale-networks-sl/zync/errors/5b561acae3f1fa00173eb3c3?event_id=5b56e1e9002721799f150000&i=gh&m=ci)

## Stacktrace

    app/models/notification.rb:35 - block in create_model
    app/models/application_record.rb:10 - block in retry_record_not_unique
    bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235 - block in transaction
    bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:194 - block in within_new_transaction
    bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:191 - within_new_transaction
    bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235 - transaction
    bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/transactions.rb:210 - transaction
    app/models/application_record.rb:9 - retry_record_not_unique
    app/models/application_record.rb:22 - retry_record_not_unique
    app/models/notification.rb:34 - create_model
    app/services/incoming_notification_service.rb:16 - block in call
    bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235 - block in transaction
    bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:194 - block in within_new_transaction
    bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:191 - within_new_transaction
    bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235 - transaction
    bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/transactions.rb:210 - transaction
    bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/transactions.rb:299 - transaction
    app/services/incoming_notification_service.rb:15 - call
    app/controllers/notifications_controller.rb:6 - update
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_controller/metal/basic_implicit_render.rb:4 - send_action
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/abstract_controller/base.rb:186 - process_action
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_controller/metal/rendering.rb:30 - process_action
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/abstract_controller/callbacks.rb:20 - block in process_action
    bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:131 - run_callbacks
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/abstract_controller/callbacks.rb:19 - process_action
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_controller/metal/rescue.rb:20 - process_action
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_controller/metal/instrumentation.rb:32 - block in process_action
    bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166 - block in instrument
    bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21 - instrument
    bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166 - instrument
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_controller/metal/instrumentation.rb:30 - process_action
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_controller/metal/params_wrapper.rb:252 - process_action
    bundle/ruby/2.4.0/gems/activerecord-5.1.6/lib/active_record/railties/controller_runtime.rb:22 - process_action
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/abstract_controller/base.rb:124 - process
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_controller/metal.rb:189 - dispatch
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_controller/metal.rb:253 - dispatch
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:49 - dispatch
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:31 - serve
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:50 - block in serve
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:33 - each
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:33 - serve
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:844 - call
    bundle/ruby/2.4.0/gems/message_bus-2.1.4/lib/message_bus/rack/middleware.rb:63 - call
    bundle/ruby/2.4.0/gems/prometheus-client-0.7.1/lib/prometheus/middleware/exporter.rb:32 - call
    bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/etag.rb:25 - call
    bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/conditional_get.rb:38 - call
    bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/head.rb:12 - call
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/callbacks.rb:26 - block in call
    bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:97 - run_callbacks
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/callbacks.rb:24 - call
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/debug_exceptions.rb:59 - call
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/show_exceptions.rb:31 - call
    bundle/ruby/2.4.0/gems/lograge-0.10.0/lib/lograge/rails_ext/rack/logger.rb:15 - call_app
    bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/rack/logger.rb:24 - block in call
    bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/tagged_logging.rb:69 - block in tagged
    bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/tagged_logging.rb:26 - tagged
    bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/tagged_logging.rb:69 - tagged
    bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/rack/logger.rb:24 - call
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/remote_ip.rb:79 - call
    bundle/ruby/2.4.0/gems/request_store-1.4.1/lib/request_store/middleware.rb:19 - call
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/request_id.rb:25 - call
    bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/runtime.rb:22 - call
    bundle/ruby/2.4.0/gems/activesupport-5.1.6/lib/active_support/cache/strategy/local_cache_middleware.rb:27 - call
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/executor.rb:12 - call
    bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/sendfile.rb:111 - call
    bundle/ruby/2.4.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/debug_locks.rb:39 - call
    bundle/ruby/2.4.0/gems/railties-5.1.6/lib/rails/engine.rb:522 - call
    bundle/ruby/2.4.0/gems/puma-3.11.4/lib/puma/configuration.rb:225 - call
    bundle/ruby/2.4.0/gems/puma-3.11.4/lib/puma/server.rb:632 - handle_request
    bundle/ruby/2.4.0/gems/puma-3.11.4/lib/puma/server.rb:446 - process_client
    bundle/ruby/2.4.0/gems/puma-3.11.4/lib/puma/server.rb:306 - block in run
    bundle/ruby/2.4.0/gems/puma-3.11.4/lib/puma/thread_pool.rb:120 - block in spawn_thread

[View full stacktrace](https://app.bugsnag.com/3scale-networks-sl/zync/errors/5b561acae3f1fa00173eb3c3?event_id=5b56e1e9002721799f150000&i=gh&m=ci)

*Created by Michal Cichra via Bugsnag*

**Comment by Martouta** [comment]
This is at least a 99% a System bug and it is already fixed and merged (although not deployed yet)

**Comment by mikz** [comment]
It was indeed triggered from outside, but that does not change that zync crashes when it shouldn't. It should report error properly and not return 500.
